[supervisord]
nodaemon=true
logfile=/app/logs/supervisord-api.log
pidfile=/tmp/supervisord-api.pid

[program:dashboard]
command=luopan-api-rs
directory=/app
autostart=true
autorestart=true
stdout_logfile=/app/logs/dashboard.log
stderr_logfile=/app/logs/dashboard.err
