import { $ } from "../dom";
import { errorMessage, request } from "../api";
import { escapeHtml, money, whole } from "../format";
import { isAdmin } from "../state";
import type { AnyRecord } from "../state";

let previewToken = "";
function rows(items: AnyRecord[], inventory = false) { return items.slice(0, 12).map((row) => `<tr><td>${escapeHtml(String(row["商品名称"] || row["商品名称"] || "—"))}</td><td>${escapeHtml(String(row.product_id || "—"))}</td><td>${inventory ? whole(row["全国可用库存"]) : money(row["成交金额"])}</td><td>${inventory ? `${Number(row["全国预计可售天数"] || 0).toFixed(1)} 天` : whole(row["访客数"])}</td></tr>`).join(""); }
export async function loadJd() { const target=$("#jd-content"); if(!target) return; try { const data=await request<AnyRecord>("/api/jd"); const s=data.summary||{}; target.innerHTML=`<section class="panel"><div class="panel-head"><div><h3>京东商品经营</h3><span>手动导入的商品经营与 RDC 库存快照</span></div></div><div class="metric-grid"><article class="metric-card"><div class="metric-label">商品行</div><div class="metric-value">${whole(s.product_rows)}</div></article><article class="metric-card"><div class="metric-label">成交金额</div><div class="metric-value">${money(s.revenue)}</div></article><article class="metric-card"><div class="metric-label">访客数</div><div class="metric-value">${whole(s.visitors)}</div></article><article class="metric-card"><div class="metric-label">库存风险</div><div class="metric-value">${whole((data.inventory_risks||[]).length)}</div></article></div>${isAdmin()?`<form id="jd-upload-form" class="order-upload-form"><label class="file-picker"><span>选择京东 RDC / 商品经营 Excel</span><input type="file" name="files" accept=".xlsx" multiple required /></label><button class="button">导入预览</button></form><div id="jd-preview"></div>`:""}<h3 class="section-title">库存风险</h3><div class="table-wrap"><table><thead><tr><th>商品</th><th>ID</th><th>全国可用库存</th><th>预计可售天数</th></tr></thead><tbody>${rows(data.inventory_risks||[],true)||"<tr><td colspan=4>暂无风险数据</td></tr>"}</tbody></table></div><h3 class="section-title">商品经营明细</h3><div class="table-wrap"><table><thead><tr><th>商品</th><th>ID</th><th>成交金额</th><th>访客数</th></tr></thead><tbody>${rows(data.products||[])||"<tr><td colspan=4>暂无经营数据</td></tr>"}</tbody></table></div></section>`; $("#jd-upload-form")?.addEventListener("submit",preview); } catch(e){target.innerHTML=`<div class="empty-panel"><strong>京东数据暂不可用</strong><span>${escapeHtml(errorMessage(e,"读取失败"))}</span></div>`;} }
async function preview(event:SubmitEvent){event.preventDefault(); const data=await request<AnyRecord>("/api/jd/imports/preview",{method:"POST",body:new FormData(event.currentTarget as HTMLFormElement)}); previewToken=String(data.preview_token||""); const files=(data.files||[]).map((f:AnyRecord)=>`${f.file_name} · ${f.kind} · ${whole(f.rows)} 行${f.known_file?"（已导入）":""}`).join("<br>"); const target=$("#jd-preview"); if(target) target.innerHTML=`<p class="order-import-message">${files}</p><button id="jd-commit" class="button button-primary">确认写入京东看板</button>`; $("#jd-commit")?.addEventListener("click",commit); }
async function commit(){if(!previewToken)return; await request("/api/jd/imports",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({preview_token:previewToken})}); previewToken=""; await loadJd();}
